name: Auto Create Pull Request from Dev to Main

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get commit details
        id: get-commit
        run: |
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
          echo "COMMIT_URL=https://github.com/${{ github.repository }}/commit/$(git log -1 --pretty=format:'%H')" >> $GITHUB_ENV
          echo "BRANCH_NAME=dev" >> $GITHUB_ENV

      - name: Check if PR already exists
        id: check-pr
        run: |
          existing_pr=$(gh pr list --state open --head dev --base main --json number --jq '.[0].number')
          if [ "$existing_pr" != "null" ] && [ "$existing_pr" != "" ]; then
            echo "pr_exists=true" >> $GITHUB_OUTPUT
            echo "pr_number=$existing_pr" >> $GITHUB_OUTPUT
          else
            echo "pr_exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        if: steps.check-pr.outputs.pr_exists == 'false'
        id: create-pr
        run: |
          pr_body="### Pull Request Details

          **Description:** ${COMMIT_MESSAGE}
          **Author:** ${COMMIT_AUTHOR}
          **Source Branch:** dev
          **Target Branch:** main
          **Commit URL:** [${COMMIT_URL}](${COMMIT_URL})

          ### Changes Made

          ${COMMIT_MESSAGE}

          ### Auto-Merge Status

          This pull request will be automatically merged after successful checks."

          pr_number=$(gh pr create \
            --title "Auto PR: ${COMMIT_MESSAGE}" \
            --body "$pr_body" \
            --head dev \
            --base main \
            --label "auto-generated,development" \
            --assignee "Atik203" \
            --json number --jq '.number')

          echo "pr_number=$pr_number" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update existing PR
        if: steps.check-pr.outputs.pr_exists == 'true'
        run: |
          pr_body="### Pull Request Details

          **Description:** ${COMMIT_MESSAGE}
          **Author:** ${COMMIT_AUTHOR}
          **Source Branch:** dev
          **Target Branch:** main
          **Commit URL:** [${COMMIT_URL}](${COMMIT_URL})

          ### Changes Made

          ${COMMIT_MESSAGE}

          ### Auto-Merge Status

          This pull request will be automatically merged after successful checks.

          **Updated:** $(date)"

          gh pr edit ${{ steps.check-pr.outputs.pr_number }} \
            --title "Auto PR: ${COMMIT_MESSAGE}" \
            --body "$pr_body"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
