name: Auto Create Pull Request from Dev to Main

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: read
  checks: read
  repository-projects: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get commit details
        id: get-commit
        run: |
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
          echo "COMMIT_URL=https://github.com/${{ github.repository }}/commit/$(git log -1 --pretty=format:'%H')" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git log -1 --pretty=format:'%H')" >> $GITHUB_ENV

      - name: Check if PR already exists
        id: check-pr
        run: |
          # Check for existing open PR from dev to main
          pr_data=$(gh pr list --head dev --base main --state open --limit 1 --json number 2>/dev/null || echo "[]")
          pr_number=$(echo "$pr_data" | jq -r '.[0].number // empty')

          if [ -n "$pr_number" ] && [ "$pr_number" != "null" ]; then
            echo "Found existing PR #$pr_number"
            echo "pr_exists=true" >> $GITHUB_OUTPUT
            echo "pr_number=$pr_number" >> $GITHUB_OUTPUT
          else
            echo "No existing PR found"
            echo "pr_exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Create Pull Request
        if: steps.check-pr.outputs.pr_exists == 'false'
        id: create-pr
        run: |
          pr_body="### Pull Request Details

          **Description:** ${COMMIT_MESSAGE}
          **Author:** ${COMMIT_AUTHOR}
          **Source Branch:** dev
          **Target Branch:** main
          **Latest Commit:** [${COMMIT_HASH:0:7}](${COMMIT_URL})

          ### Changes Made

          ${COMMIT_MESSAGE}

          ### Auto-Merge Status

          This pull request will be automatically merged after successful checks.

          ---
          *Auto-generated on $(date)*"

          gh pr create \
            --title "Auto PR: ${COMMIT_MESSAGE}" \
            --body "$pr_body" \
            --head dev \
            --base main \
            --label "auto-generated" \
            --assignee "Atik203"
            
          echo "✅ Created new pull request"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Update existing PR
        if: steps.check-pr.outputs.pr_exists == 'true'
        run: |
          pr_body="### Pull Request Details

          **Description:** ${COMMIT_MESSAGE}
          **Author:** ${COMMIT_AUTHOR}
          **Source Branch:** dev
          **Target Branch:** main
          **Latest Commit:** [${COMMIT_HASH:0:7}](${COMMIT_URL})

          ### Changes Made

          ${COMMIT_MESSAGE}

          ### Auto-Merge Status

          This pull request will be automatically merged after successful checks.

          ---
          *Last updated on $(date)*"

          gh pr edit ${{ steps.check-pr.outputs.pr_number }} \
            --title "Auto PR: ${COMMIT_MESSAGE}" \
            --body "$pr_body"
            
          gh pr comment ${{ steps.check-pr.outputs.pr_number }} \
            --body "🔄 **Updated with latest changes**
            
          **New commit:** [${COMMIT_HASH:0:7}](${COMMIT_URL})
          **Message:** ${COMMIT_MESSAGE}
          **Author:** ${COMMIT_AUTHOR}"
            
          echo "✅ Updated existing pull request #${{ steps.check-pr.outputs.pr_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
